import "./router";
import "./pages";
import "./pages/join-room";
import "./pages/insert-name";
import "./pages/game-room";
import "./pages/game-room-two";
import "./pages/game-room-two-bis";
import "./pages/game-room-three";
import "./pages/game-results";
import "./pages/rejected-page";
import { buttonComponent } from "./components/custom-button";
import { moveComponent } from "./components/move";
import { timeCounterComponent } from "./components/time-counter";
import { resultScoreComponent } from "./components/result-score";
import { state } from "./state";
(function () {
  buttonComponent();
  timeCounterComponent();
  resultScoreComponent();
  moveComponent();
  state.init();
})();
